#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
ASSIGNMENT=wp3
#ASSIGNMENT=project
TEAM_MEMBERS_CSV="Akshat Singhal[aksinghal@cs.stonybrook.edu; 111496103]; Ashish Yadav[ashyadav@cs.stonybrook.edu; 111486009]; Vaibhav Rustagi[vrustagi@cs.stonybrook.edu; 111462063]"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
